# Generated by Django 4.0.5 on 2022-11-11 23:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpactUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(db_column='firstname', max_length=50)),
                ('last_name', models.CharField(db_column='lastname', max_length=50)),
                ('mobile_number', models.CharField(max_length=13)),
                ('email', models.CharField(max_length=100)),
                ('member_type', models.CharField(choices=[('Community', 'Community'), ('InnovationHub', 'InnovationHub')], default='Community', max_length=100)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
