# Generated by Django 4.0.5 on 2022-11-11 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_empactuser_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empactuser',
            name='country',
            field=models.CharField(default='Kenya', max_length=100),
        ),
    ]
