# Generated by Django 4.0.5 on 2022-11-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_post_id_post_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.AutoField(default='2020', primary_key=True, serialize=False, unique=True),
        ),
    ]
