# Generated by Django 4.0.5 on 2022-11-25 19:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0005_empactuser_profile_pic_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('community_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('community_name', models.CharField(max_length=100)),
                ('verified', models.BooleanField(default=True)),
                ('community_description', models.CharField(max_length=400)),
                ('country', models.CharField(default='Kenya', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('community_admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='community', to='authentication.empactuser')),
                ('members', models.ManyToManyField(blank=True, related_name='communitymember', to='authentication.empactuser')),
            ],
            options={
                'verbose_name_plural': 'Communities',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('project_name', models.CharField(max_length=100)),
                ('project_description', models.CharField(max_length=400)),
                ('project_status', models.CharField(choices=[('Initiated', 'Initiated'), ('Running', 'Running'), ('Completed', 'Completed')], default='Running', max_length=10)),
                ('lifes_impacted', models.CharField(blank=True, max_length=20, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project', to='community.community')),
                ('project_coodinator', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project', to='authentication.empactuser')),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='CommunityMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_file', models.CharField(max_length=400)),
                ('media_type', models.CharField(choices=[('Image', 'Image'), ('Video', 'Video'), ('Document', 'Document')], default='Image', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('commuinty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community', to='community.community')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityComment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('show', models.BooleanField(default=True)),
                ('body', models.TextField()),
                ('image_url', models.CharField(blank=True, max_length=300, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communitycomments', to='authentication.empactuser')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communitycomments', to='community.community')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
