# Generated by Django 4.0.5 on 2022-11-25 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_empactuser_profile_pic_url'),
        ('community', '0003_rename_commuinity_project_community'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_coodinator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='project', to='authentication.empactuser'),
        ),
    ]
