# Generated by Django 4.1.4 on 2023-05-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_alter_project_project_coodinator'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='community_img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
